### ISSUE TITLE
Credential Handler registration API Shape

### ISSUE THREAD

**Issue by dlongley** [w3c-ccg/credential-handler-api#2]
I'm hoping to model the Credential Handler API after both the [Payment Handler API](https://www.w3.org/TR/payment-handler) and the [Credential Management API](https://w3c.github.io/webappsec-credential-management/) as these specs seem to be getting traction and implementation at W3C.

For those unfamiliar with the Payment Handler API, it is an API that works in conjunction with the [Payment Request API](https://w3c.github.io/payment-request/) to enable third party websites to provide Payment Handlers (these can be thought of as Payment Apps) to help users pay for things on other websites. The flow looks like this:

1. User visits a website that can register a payment handler. The user grants "paymenthandler" permission to that website which allows it to install a payment handler that can be used later when the user needs to pay for things on the Web. The payment handler may be like a "payment wallet" where you can keep all of your credit cards (or other "payment instruments") in one place or it may be like a proprietary payment service, like PayPal.

2. The user visits a merchant's website to buy something. When they click "buy" the merchant's site uses the Payment Request API to bring up a payment-specific UI in the browser. This UI shows the user all of the payment instruments that have been registered by payment handlers they've authorized in the past. So, for example, you may see the ability to "Pay with PayPal" or you may see "Pay with Visa *1234 via BestPaymentWallet.com".

3. Once the user selects the payment instrument of their choice, the browser sends the payment request to the associated payment handler. This is where the third party website takes over and may show the user a "payment app" UI to help them complete the payment. Then the payment handler sends the "payment response" back to the browser which forwards it to the merchant's website where payment will be completed (or where it will be confirmed that it was already completed, depending on the payment method).

***Much of this flow can be generalized to this:***

1. A user visits website A, grants "handler" permission to A, and A registers a "handler" for requests of type "X".
2. The user visits website B, receives a request of type X and the browser shows the user all handlers of type X for them to make a choice. The user selects A.
3. A is given the request and shows the user a UI where they do whatever their part is to fulfill the request and the response is sent to the browser which forwards it to website B.

***Now, it should start becoming clear that we can use the same flow for sharing credentials (or "profiles").***

1. A user visits website A (a ***credential repository***), grants "credentialhandler" permission to A, and A registers a "credential handler" for credential requests.
2. The user visits website B (an ***inspector-verifier***), receives a credential request and the browser shows the user all credential handlers to make a choice. The user selects A.
3. A is given the credential request and shows the user a UI where they select the credentials they want to send. The response is sent to the browser which forwards it to website B.

This is potentially a common flow that goes far beyond just payment and credentials. It would be great to have a generic API that would allow people to more rapidly innovate on these sorts of flows without needing to make any changes to browsers. But, it's not our immediate goal to create that generic API. I do, however, recommend that we try and structure both what we implement and what we spec out to be as close as possible to something that could become more generic in the future.

So, what I am proposing here is that we follow at least the structure that the Web Payments WG has gone with, and I think the parallels are already there to do exactly this or something very close.

Right now, the Payment Handler API is not implemented in browsers (but is supposedly in the works). But the Payment Request API is. The Payment Request API that is implemented in browsers today only supports the "basic-card" payment method (paying with a credit card) and it uses a built-in "payment handler" to do this.

The Credential Management API isn't *exactly* the same as the Payment Request API, but it is a pretty close analog. It currently lets websites store credentials and retrieve them, but not from third party "credential handler" websites. It has extension points in the spec, but no concept of delegation like the Payment Handler API (yet).

Our API could be the Payment Handler API equivalent -- a counterpart to the Credential Management API called the Credential Handler API.

I will add more comments with specific code examples.

**Comment by dlongley** [comment]
So, now on to some code examples. The Payment Handler API has a registration API that lets devs for websites that want to provide payment handlers (e.g. payment wallet websites/proprietary payment websites, etc) that works like this:

```js
async function install() {
  // ensure permission has been granted
  const result = await PaymentManager.requestPermission();
  if(result !== 'granted') {
    throw new Error('Permission denied.');
  }
  
  // get payment handler registration
  const {registration} = await navigator.serviceWorker.register(
    '/register/payment-handler.js');

  // add a payment instrument
  const instrumentKey = 'c8126178-3bba-4d09-8f00-0771bcfd3b11';
  await self.registration.paymentManager.paymentInstruments.set(
    instrumentKey, {
      name: 'My Visa *1234',
      enabledMethods: ['visa'],
      icons: [{
        src: '../foo/icon/lowres.webp',
        sizes: '48x48',
        type: 'image/webp'
      }]
    }
  });
}
```

This uses Service Workers but you don't really need to understand those right now. Just think of the registration code like this:

1. You register some endpoint (the "payment handler") with some JavaScript that the browser will run so it can receive a payment request when the user selects an associated payment instrument.
2. You register one or more payment instruments with some details the browser can show in the UI so the user will pick it. The browser will automatically store an association between the payment instrument and the particular payment handler so it's JavaScript will run when the instrument is chosen.

Now, there's some code that you have to actually write in the payment handler to receive and handle a payment request, should one come your way. This happens through events -- the payment request is sent via a `paymentrequest` event to the payment handler (Service Worker). A very shortened example:

```js
self.addEventListener('paymentrequest', event => {
  console.log('got payment request event', event);
  
  // TODO: do things with `event.methodData` and `event.instrumentKey`
  // (payment method data), etc.

  event.respondWith(new Promise((resolve, reject) => {
    resolve({
      methodName: 'basic-card',
      details: {
        cardHolderName: 'Pat Smith',
        cardNumber: '1232343451234',
        expiryMonth: '12',
        expiryYear: '2020',
        cardSecurityCode: '123'
      }
    });
  });
});
```

In this example we just respond to the payment request with some hard-coded credit card credentials. Normally, we would look at the payment instrument key provided in the event and look it up -- and maybe open a window and show a UI to let the user do things. There are other examples of how to do this in the Payment Handler API spec if you want to look.

Now with this background -- we can look at how registration could look in three different scenarios:

## Payment Handler Registration
```js
registration.paymentManager.instruments.set(
  'c8126178-3bba-4d09-8f00-0771bcfd3b11', {
    name: 'Name to present to user for this choice',
    icons: ['icons to present to user for this choice'],
    enabledMethods: ['decentralized/did/profile'],
    capabilities: { ... }
  }
});
```

## Credential Handler Registration?
```js
registration.credentialManager.stores.set(
  'c8126178-3bba-4d09-8f00-0771bcfd3b11', {
    name: 'Name to present to user for this choice',
    icons: ['icons to present to user for this choice'],
    enabledTypes: ['decentralized?/did?/profile?'],
    capabilities: { ... }
  }
});

## Generic Handler Registration?
registration.webRequestHandlers.set(
  'c8126178-3bba-4d09-8f00-0771bcfd3b11', {
    name: 'Name of the handler to show to the user',
    icons: ['icons to present to the user for this choice'],
    enabledTypes: ['requestType1', 'requestType2'],
    capabilities: { ... }
  }
})
```

The Credential Management API uses a `CredentialStore` interface that is exposed via `navigator.credentials`. We could potentially tap into this interface to provide alternative "stores" (credential repositories). This could be how we register "credential handlers" -- and it would be very close to what happens with payments.

Note: I also threw in some generic "web request" registration code there -- just to show that we could potentially make this more general to the point where only the "request type" really matters to the browser. I'm not saying we take that on, just pointing out that it's a future direction to unify the API across different types of requests on the Web.

I'm open to hearing what people think about the above snippet as the way we go about registering credential handlers. The code for handling credential requests would also be quite similar:

```js
self.addEventListener('credentialrequest', event => {
  console.log('got credential request event', event);
  
  // TODO: do things with `event.credentialQuery`, whatever else

  event.respondWith(new Promise((resolve, reject) => {
    resolve({
      id: 'did:1234...',
      credential: [{ ... }]
    });
  });
});
```

**Comment by dlongley** [comment]
The Credential Management API has been updated since I last looked at it -- and it looks like there may be a hook for us to use called `discovery`:

> The Credential interface object has an internal slot named [[discovery]], representing the mechanism by which the user agent can collect credentials of a given type. Its value is either "credential store" or "remote". The former value means that all available credential information is stored in the user agent’s credential store, while the latter means that the user agent can discover credentials outside of those explicitly represented in the credential store via interaction with some external device or service.

Essentially, we can extend `Credential` and set `discovery` to `remote`. I'll keep looking into the spec to see how to tie in the pieces we need. Note: Existing implementations of the [credentials polyfill](https://github.com/Spec-Ops/credentials-polyfill) already extend `Credential` to create an `IdentityCredential`. We'll need to bikeshed this name at some point and figure out exactly what functionality we want to expose with it.

**Comment by dlongley** [comment]
Note that we need a "catch all" for the `XCredential` type that we define, as the actual number of credentials we support is unbounded. We're looking for a "class" or "type" of Credential like `DecentralizedCredential` or `IdentityCredential` or `VerifiableProfileCredential` or or `VerifiableClaimCredential` or `AttributeCredential`, not something like `DriversLicenseCredential`. It should be something that more or less maps to a Verifiable Profile. I can see the language here causing some potential confusion/consternation, but if we are to use the Credential Management API, we'll need to make it work.

Whenever this new XCredential is, it should be the "type" of credential that, when requested, results in user seeing a set of choices that map to credential handlers that can fulfill the request. So we should expect the query for this kind of credential to say that an "xcredential" is desired -- and, specifically, we want that "xcredential" to contain these other credentials in it. This is why "xcredential" may be best though of as a Verifiable Profile. A website would request a VerifiableProfile containing attributes X, Y, Z from the user -- and their chosen credential handler should fulfill this request by creating the profile and including the appropriate credentials that assert those attributes via claims.

**Comment by dlongley** [comment]
If we want "profiles" to be exposed as choices in a UI -- when selecting which credential handler to use to fulfill a credential request -- then we would want to register `profiles` instead of `stores`:

```js
registration.credentialManager.profiles.set(
  // could be a DID or something else entirely and have no meaning
  // beyond selection identification (only meaningful to the
  // credential handler that registered it)
  'did:foo-method:1234-123123123-123-1231', {
    name: 'Name to present to user for this choice',
    icons: ['icons to present to user for this choice'],
    enabledTypes: ['decentralized?/did?/profile?'],
    capabilities: { ... }
  }
});
```

I'm leaning more in this direction because it requires fewer clicks by the user. They can select the identifier they want to work with upfront and send that to the credential handler to build the profile (with credentials) to present. The terminology here is a little fuzzy because we're not registering "profiles" -- we're registering identifiers that the user can select to build a profile. So we need a little naming work here to sort that out.

Note that this could still be done in a generic way without thinking of these as "profiles" but simply as items that credential handlers can register that the user will select and pass to the handler. That our particular credential handlers will want identifiers for use in profiles is not relevant at that level. The credential handler is just registering some visual aids that will map to it and can have meaning to it once selected. This information could be considered when working on the terminology.

**Comment by dlongley** [comment]
Maybe what gets registered is just another "authentication option" -- essentially a "Credential" at the `Credential Management API` layer, but it needs additional information appended to it -- specifically, a `profile` property -- that can only be added by the credential handler. So it's like a "partial Credential" that the user can select, but it is not fully "built" until a credential handler provides the missing pieces.

This would mean that registering such a credential would make it appear in the credential selector screen but, when it is actually selected by the user, additional credential handler code must run to fully populate it. I'll look into the Credential Management API spec to see if this approach is covered by its extension points. Either way, that could actually be the place where we tie in "credential handlers" -- and it would potentially be a better fit. This would not solve the naming problem -- it's still unclear what to call these "partial credentials" ... `PartialCredential` is weird, `DelegatedCredential` isn't great, maybe `DeferredCredential`... welcome to suggestions. Hopefully the concept here is clear.

**Comment by dlongley** [comment]
There is a section in the Credential Management API spec that talks about users selecting a "type" of credential that then allows for subsequent custom selection of a specific Credential:

Steps 5.7-5.9 
https://w3c.github.io/webappsec-credential-management/#algorithm-request

This isn't exactly what I think we're looking for, however. We're not looking to create a new "type" of credential for every "aspect" a user may have, but rather, a single type of "DeferredCredential" or "Indicator" (similar to `PaymentInstrument` in the Web Payments work) that, when selected, will be passed to a triggered a custom credential handler that is responsible for providing the actual credential. This could also be modeled as a `DeferredCredential` with some `type` and `data` properties that get populated by a credential handler, where we would use the `type` "VerifiableProfile" and the data would be the VerifiableProfile itself. Other handlers could do something different.

**Comment by kimdhamilton** [comment]
I'm still getting versed in this project, but from my 40K foot view, this design looks very clean and solid. I like the parallels between this approach and the Payment Handler API. 

Also +1 on the term `DeferredCredential` -- it sounds like a natural match for the behavior you described

**Comment by dlongley** [comment]
A demo of the current polyfill implementation can now be found here:

https://credential-repository.demo.digitalbazaar.com

**Comment by dlongley** [comment]
Closing as the current registration API is in use by several parties. Another issue can be opened if it needs to change.
