### ISSUE TITLE
Credential Selection Criteria

### ISSUE THREAD

**Issue by AdamSobieski** [w3c-ccg/credential-handler-api#4]
Might a _credential selection criteria_, modifying a query, be of use for filtering which credentials that a user might utilize in a credential repository (digital wallet) to compose a verifiable profile? What data and metadata do credentials have for this purpose?

**Comment by dlongley** [comment]
Closing as this topic has moved to another repo (and may eventually be picked up as a different CCG work item): https://github.com/digitalbazaar/vp-request-spec
