### ISSUE TITLE
VerifiableProfile query format

### ISSUE THREAD

**Issue by dlongley** [w3c-ccg/credential-handler-api#5]
While `VerifiableProfile` is only one possible type of `WebCredential`, it would be good to discuss what the query format for such a credential would look like -- which we can do here until we have a separate repo specific for a `VerifiableProfile` datatype extension.

There are at least three top-level types of information a verifier may want to request in a query for a VerifiableProfile:

1. Attributes/types of credentials/claims desired
2. Trusted issuers
3. Terms of use

A quick strawman:

```js
{
  web: {
    VerifiableProfile: {
      TBD: {...},                   // attributes/types of creds/claims
      trustedIssuers: [...],
      termsOfUse: {...}
   }
}
```

In the TBD section, one approach would include allowing the specification of various attributes from some ontology/vocabularies as JSON keys.

**Comment by dlongley** [comment]
An example of what's happening in the demo now:

https://github.com/digitalbazaar/credential-handler-demo/blob/master/angular-credential-verifier/components/home-component.js#L20-L30

```js
      self.credential = await navigator.credentials.get({
        web: {
          VerifiableProfile: {
            '@context': {
              'br': 'urn:bedrock:',
              'cred': 'https://w3id.org/credentials#'
            },
            'br:test:passport': {'cred:isOptional': true}
          }
        }
      });
```

We probably need another nesting level under `VerifiableProfile` for what is mentioned (TBD, trustedIssuers, termsOfUse, etc) above -- and what's there presently would move somewhere under `TBD`.

**Comment by kimdhamilton** [comment]
@ChristopherA: just making sure you see this because it's relevant to our BTCR with VCs prototype.

**Comment by AdamSobieski** [comment]
Here are some ideas:

A set of attributes may be requested; each attribute may be optional or required for a request; for each attribute, one or a number of corroborating credentials may be required; for each attribute, data and metadata about acceptable credentials and issuers may be specified or described.

**Comment by dlongley** [comment]
Closing as this topic has moved to another repo (and may eventually be picked up as a different CCG work item): https://github.com/digitalbazaar/vp-request-spec
